version: 2.1

workflows:
  main:
    jobs:
      - sync-to-huggingface:
          context:
            - HuggingFace
          filters:
            branches:
              only:
                - main

jobs:
  sync-to-huggingface:
    docker:
     - image: alpine
    resource_class: small
    steps:
      - run: 
          name: install git
          command: apk update && apk add openssh-client git
      - checkout
      - run:
          name: push to Huggingface hub
          command: |
                  git config user.email "lavin.github@outlook.com" 
                  git config user.name "CCI Bot" 
                  git push -f https://lavin-ds:${HF_PERSONAL_TOKEN}@huggingface.co/spaces/lavin-ds/HuggingSpace main